"""empty message

Revision ID: 53693f32af50
Revises: 7a6d9853e986
Create Date: 2021-10-21 18:52:51.927433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53693f32af50'
down_revision = '7a6d9853e986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_parent_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('notes_user_id_fkey', 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key('notes_user_id_fkey', 'notes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_parent_id_fkey', 'comments', 'comments', ['parent_id'], ['id'])
    # ### end Alembic commands ###
