"""empty message

Revision ID: 369294b402fb
Revises: 024ff861b0be
Create Date: 2021-10-12 19:04:57.440911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '369294b402fb'
down_revision = '024ff861b0be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('note_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'notes', ['note_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['id'])
    op.drop_column('comments', 'item_type')
    op.drop_column('comments', 'item_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('item_type', postgresql.ENUM('note', 'comment', name='item_types'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'parent_id')
    op.drop_column('comments', 'note_id')
    # ### end Alembic commands ###
